# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_input.ui'
#
# Created: Sat Oct  3 00:16:01 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName(_fromUtf8("Editor"))
        Editor.resize(1085, 800)
        self.gridLayout = QtGui.QGridLayout(Editor)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Editor)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1017, 667))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem1 = QtGui.QSpacerItem(357, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 3, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox_4)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_8.addWidget(self.comboBox, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(120, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 1, 1, 1)
        self.toolButton_5 = QtGui.QToolButton(self.groupBox_4)
        self.toolButton_5.setMinimumSize(QtCore.QSize(0, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Metadata_editor/icons/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon)
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.gridLayout_8.addWidget(self.toolButton_5, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 114, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 1, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 400))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.scrollArea_2 = QtGui.QScrollArea(self.groupBox_2)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(500, 0))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 498, 362))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.toolButton = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.toolButton.setIcon(icon)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout_6.addWidget(self.toolButton, 0, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_12.addWidget(self.lineEdit_3, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_10.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_11.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_11.addWidget(self.checkBox, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_14.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_9, 3, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_5, 0, 0, 3, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 1, 1, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(172, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 2, 1, 1)
        self.listWidget = QtGui.QListWidget(self.groupBox_2)
        self.listWidget.setMinimumSize(QtCore.QSize(380, 0))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_5.addWidget(self.listWidget, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.dateEdit = QtGui.QDateEdit(self.groupBox_3)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout_7.addWidget(self.dateEdit, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 0, 3, 1, 1)
        self.toolButton_4 = QtGui.QToolButton(self.groupBox_3)
        self.toolButton_4.setMinimumSize(QtCore.QSize(0, 25))
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.gridLayout_7.addWidget(self.toolButton_4, 0, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(75, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem7, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.groupBox_2_1 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2_1.setObjectName(_fromUtf8("groupBox_2_1"))
        self.gridLayout_24 = QtGui.QGridLayout(self.groupBox_2_1)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.scrollArea_2_1 = QtGui.QScrollArea(self.groupBox_2_1)
        self.scrollArea_2_1.setWidgetResizable(True)
        self.scrollArea_2_1.setObjectName(_fromUtf8("scrollArea_2_1"))
        self.scrollAreaWidgetContents_2_1 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2_1.setGeometry(QtCore.QRect(0, 0, 1001, 693))
        self.scrollAreaWidgetContents_2_1.setObjectName(_fromUtf8("scrollAreaWidgetContents_2_1"))
        self.gridLayout_25 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2_1)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.groupBox_2_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2_2.setSizePolicy(sizePolicy)
        self.groupBox_2_2.setObjectName(_fromUtf8("groupBox_2_2"))
        self.gridLayout_26 = QtGui.QGridLayout(self.groupBox_2_2)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.lineEdit_2_1 = QtGui.QLineEdit(self.groupBox_2_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_2_1.setSizePolicy(sizePolicy)
        self.lineEdit_2_1.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEdit_2_1.setObjectName(_fromUtf8("lineEdit_2_1"))
        self.gridLayout_26.addWidget(self.lineEdit_2_1, 1, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem8, 1, 2, 1, 1)
        self.toolButton_2_1 = QtGui.QToolButton(self.groupBox_2_2)
        self.toolButton_2_1.setIcon(icon)
        self.toolButton_2_1.setObjectName(_fromUtf8("toolButton_2_1"))
        self.gridLayout_26.addWidget(self.toolButton_2_1, 1, 1, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_2_2, 0, 0, 1, 1)
        self.groupBox_2_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2_1)
        self.groupBox_2_4.setObjectName(_fromUtf8("groupBox_2_4"))
        self.gridLayout_28 = QtGui.QGridLayout(self.groupBox_2_4)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.textEdit = QtGui.QTextEdit(self.groupBox_2_4)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_28.addWidget(self.textEdit, 1, 0, 1, 1)
        self.toolButton_2_5 = QtGui.QToolButton(self.groupBox_2_4)
        self.toolButton_2_5.setIcon(icon)
        self.toolButton_2_5.setObjectName(_fromUtf8("toolButton_2_5"))
        self.gridLayout_28.addWidget(self.toolButton_2_5, 1, 1, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_2_4, 2, 0, 1, 1)
        self.groupBox_2_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2_1)
        self.groupBox_2_3.setMinimumSize(QtCore.QSize(0, 210))
        self.groupBox_2_3.setObjectName(_fromUtf8("groupBox_2_3"))
        self.gridLayout_27 = QtGui.QGridLayout(self.groupBox_2_3)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.scrollArea_2_2 = QtGui.QScrollArea(self.groupBox_2_3)
        self.scrollArea_2_2.setWidgetResizable(True)
        self.scrollArea_2_2.setObjectName(_fromUtf8("scrollArea_2_2"))
        self.scrollAreaWidgetContents_2_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2_2.setGeometry(QtCore.QRect(0, 0, 955, 172))
        self.scrollAreaWidgetContents_2_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2_2"))
        self.gridLayout_37 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2_2)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.toolButton_2_4 = QtGui.QToolButton(self.scrollAreaWidgetContents_2_2)
        self.toolButton_2_4.setIcon(icon)
        self.toolButton_2_4.setObjectName(_fromUtf8("toolButton_2_4"))
        self.gridLayout_37.addWidget(self.toolButton_2_4, 0, 2, 1, 1)
        self.groupBox_2_7 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2_2)
        self.groupBox_2_7.setObjectName(_fromUtf8("groupBox_2_7"))
        self.gridLayout_34 = QtGui.QGridLayout(self.groupBox_2_7)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.groupBox_2_10 = QtGui.QGroupBox(self.groupBox_2_7)
        self.groupBox_2_10.setObjectName(_fromUtf8("groupBox_2_10"))
        self.gridLayout_36 = QtGui.QGridLayout(self.groupBox_2_10)
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        self.lineEdit_2_2 = QtGui.QLineEdit(self.groupBox_2_10)
        self.lineEdit_2_2.setObjectName(_fromUtf8("lineEdit_2_2"))
        self.gridLayout_36.addWidget(self.lineEdit_2_2, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_2_10, 0, 1, 1, 1)
        self.groupBox_2_9 = QtGui.QGroupBox(self.groupBox_2_7)
        self.groupBox_2_9.setObjectName(_fromUtf8("groupBox_2_9"))
        self.gridLayout_35 = QtGui.QGridLayout(self.groupBox_2_9)
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.lineEdit_2_3 = QtGui.QLineEdit(self.groupBox_2_9)
        self.lineEdit_2_3.setObjectName(_fromUtf8("lineEdit_2_3"))
        self.gridLayout_35.addWidget(self.lineEdit_2_3, 0, 0, 1, 1)
        self.pushButton_2_random = QtGui.QPushButton(self.groupBox_2_9)
        self.pushButton_2_random.setObjectName(_fromUtf8("pushButton_2_random"))
        self.gridLayout_35.addWidget(self.pushButton_2_random, 0, 1, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_2_9, 0, 0, 1, 1)
        self.gridLayout_37.addWidget(self.groupBox_2_7, 0, 0, 2, 1)
        self.scrollArea_2_2.setWidget(self.scrollAreaWidgetContents_2_2)
        self.gridLayout_27.addWidget(self.scrollArea_2_2, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_2_3, 1, 0, 1, 1)
        self.groupBox_2_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2_1)
        self.groupBox_2_6.setObjectName(_fromUtf8("groupBox_2_6"))
        self.gridLayout_32 = QtGui.QGridLayout(self.groupBox_2_6)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.scrollArea_2_4 = QtGui.QScrollArea(self.groupBox_2_6)
        self.scrollArea_2_4.setWidgetResizable(True)
        self.scrollArea_2_4.setObjectName(_fromUtf8("scrollArea_2_4"))
        self.scrollAreaWidgetContents_2_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2_5.setGeometry(QtCore.QRect(0, 0, 313, 76))
        self.scrollAreaWidgetContents_2_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_2_5"))
        self.gridLayout_33 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2_5)
        self.gridLayout_33.setObjectName(_fromUtf8("gridLayout_33"))
        self.comboBox_2 = QtGui.QComboBox(self.scrollAreaWidgetContents_2_5)
        self.comboBox_2.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_33.addWidget(self.comboBox_2, 0, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem9, 0, 2, 1, 1)
        self.toolButton_2_11 = QtGui.QToolButton(self.scrollAreaWidgetContents_2_5)
        self.toolButton_2_11.setIcon(icon)
        self.toolButton_2_11.setObjectName(_fromUtf8("toolButton_2_11"))
        self.gridLayout_33.addWidget(self.toolButton_2_11, 0, 1, 1, 1)
        self.scrollArea_2_4.setWidget(self.scrollAreaWidgetContents_2_5)
        self.gridLayout_32.addWidget(self.scrollArea_2_4, 0, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem10, 0, 3, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem11, 0, 2, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_2_6, 4, 0, 1, 1)
        self.groupBox_2_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2_1)
        self.groupBox_2_5.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_2_5.setObjectName(_fromUtf8("groupBox_2_5"))
        self.gridLayout_29 = QtGui.QGridLayout(self.groupBox_2_5)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.scrollArea_2_3 = QtGui.QScrollArea(self.groupBox_2_5)
        self.scrollArea_2_3.setWidgetResizable(True)
        self.scrollArea_2_3.setObjectName(_fromUtf8("scrollArea_2_3"))
        self.scrollAreaWidgetContents_2_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2_3.setGeometry(QtCore.QRect(0, 0, 955, 112))
        self.scrollAreaWidgetContents_2_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_2_3"))
        self.gridLayout_30 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2_3)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.toolButton_2_8 = QtGui.QToolButton(self.scrollAreaWidgetContents_2_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Metadata_editor/icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2_8.setIcon(icon1)
        self.toolButton_2_8.setObjectName(_fromUtf8("toolButton_2_8"))
        self.gridLayout_30.addWidget(self.toolButton_2_8, 0, 4, 1, 1)
        self.toolButton_2_6 = QtGui.QToolButton(self.scrollAreaWidgetContents_2_3)
        self.toolButton_2_6.setIcon(icon)
        self.toolButton_2_6.setObjectName(_fromUtf8("toolButton_2_6"))
        self.gridLayout_30.addWidget(self.toolButton_2_6, 0, 1, 1, 1)
        self.toolButton_2_7 = QtGui.QToolButton(self.scrollAreaWidgetContents_2_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Metadata_editor/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2_7.setIcon(icon2)
        self.toolButton_2_7.setObjectName(_fromUtf8("toolButton_2_7"))
        self.gridLayout_30.addWidget(self.toolButton_2_7, 0, 3, 1, 1)
        self.groupBox_2_13 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2_3)
        self.groupBox_2_13.setObjectName(_fromUtf8("groupBox_2_13"))
        self.gridLayout_31 = QtGui.QGridLayout(self.groupBox_2_13)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.lineEdit_2_6 = QtGui.QLineEdit(self.groupBox_2_13)
        self.lineEdit_2_6.setObjectName(_fromUtf8("lineEdit_2_6"))
        self.gridLayout_31.addWidget(self.lineEdit_2_6, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_2_13, 0, 0, 1, 1)
        self.scrollArea_2_3.setWidget(self.scrollAreaWidgetContents_2_3)
        self.gridLayout_29.addWidget(self.scrollArea_2_3, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_2_5, 3, 0, 1, 1)
        self.scrollArea_2_1.setWidget(self.scrollAreaWidgetContents_2_1)
        self.gridLayout_24.addWidget(self.scrollArea_2_1, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_2_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_42 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_42.setObjectName(_fromUtf8("gridLayout_42"))
        spacerItem12 = QtGui.QSpacerItem(20, 596, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_42.addItem(spacerItem12, 1, 0, 1, 1)
        self.groupBox_3_1 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3_1.setObjectName(_fromUtf8("groupBox_3_1"))
        self.gridLayout_43 = QtGui.QGridLayout(self.groupBox_3_1)
        self.gridLayout_43.setObjectName(_fromUtf8("gridLayout_43"))
        self.groupBox_3_2 = QtGui.QGroupBox(self.groupBox_3_1)
        self.groupBox_3_2.setObjectName(_fromUtf8("groupBox_3_2"))
        self.gridLayout_44 = QtGui.QGridLayout(self.groupBox_3_2)
        self.gridLayout_44.setObjectName(_fromUtf8("gridLayout_44"))
        self.comboBox_3_1 = QtGui.QComboBox(self.groupBox_3_2)
        self.comboBox_3_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_3_1.setObjectName(_fromUtf8("comboBox_3_1"))
        self.gridLayout_44.addWidget(self.comboBox_3_1, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_44.addItem(spacerItem13, 0, 1, 1, 1)
        self.toolButton_3_1 = QtGui.QToolButton(self.groupBox_3_2)
        self.toolButton_3_1.setIcon(icon)
        self.toolButton_3_1.setObjectName(_fromUtf8("toolButton_3_1"))
        self.gridLayout_44.addWidget(self.toolButton_3_1, 0, 2, 1, 1)
        self.toolButton_3_2 = QtGui.QToolButton(self.groupBox_3_2)
        self.toolButton_3_2.setIcon(icon2)
        self.toolButton_3_2.setObjectName(_fromUtf8("toolButton_3_2"))
        self.gridLayout_44.addWidget(self.toolButton_3_2, 0, 3, 1, 1)
        self.toolButton_3_3 = QtGui.QToolButton(self.groupBox_3_2)
        self.toolButton_3_3.setIcon(icon1)
        self.toolButton_3_3.setObjectName(_fromUtf8("toolButton_3_3"))
        self.gridLayout_44.addWidget(self.toolButton_3_3, 0, 4, 1, 1)
        self.gridLayout_43.addWidget(self.groupBox_3_2, 0, 0, 1, 1)
        self.gridLayout_42.addWidget(self.groupBox_3_1, 0, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_42.addItem(spacerItem14, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_45 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_45.setObjectName(_fromUtf8("gridLayout_45"))
        self.groupBox_4_1 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_4_1.setObjectName(_fromUtf8("groupBox_4_1"))
        self.gridLayout_46 = QtGui.QGridLayout(self.groupBox_4_1)
        self.gridLayout_46.setObjectName(_fromUtf8("gridLayout_46"))
        self.groupBox_4_2 = QtGui.QGroupBox(self.groupBox_4_1)
        self.groupBox_4_2.setObjectName(_fromUtf8("groupBox_4_2"))
        self.gridLayout_47 = QtGui.QGridLayout(self.groupBox_4_2)
        self.gridLayout_47.setObjectName(_fromUtf8("gridLayout_47"))
        self.scrollArea_4_1 = QtGui.QScrollArea(self.groupBox_4_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4_1.sizePolicy().hasHeightForWidth())
        self.scrollArea_4_1.setSizePolicy(sizePolicy)
        self.scrollArea_4_1.setWidgetResizable(True)
        self.scrollArea_4_1.setObjectName(_fromUtf8("scrollArea_4_1"))
        self.scrollAreaWidgetContents_4_1 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4_1.setGeometry(QtCore.QRect(0, 0, 98, 45))
        self.scrollAreaWidgetContents_4_1.setObjectName(_fromUtf8("scrollAreaWidgetContents_4_1"))
        self.gridLayout_48 = QtGui.QGridLayout(self.scrollAreaWidgetContents_4_1)
        self.gridLayout_48.setObjectName(_fromUtf8("gridLayout_48"))
        self.comboBox_4_1 = QtGui.QComboBox(self.scrollAreaWidgetContents_4_1)
        self.comboBox_4_1.setObjectName(_fromUtf8("comboBox_4_1"))
        self.gridLayout_48.addWidget(self.comboBox_4_1, 1, 0, 1, 1)
        self.scrollArea_4_1.setWidget(self.scrollAreaWidgetContents_4_1)
        self.gridLayout_47.addWidget(self.scrollArea_4_1, 1, 0, 1, 5)
        self.scrollArea_4_2 = QtGui.QScrollArea(self.groupBox_4_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_4_2.setSizePolicy(sizePolicy)
        self.scrollArea_4_2.setWidgetResizable(True)
        self.scrollArea_4_2.setObjectName(_fromUtf8("scrollArea_4_2"))
        self.scrollAreaWidgetContents_4_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents_4_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_4_2"))
        self.gridLayout_49 = QtGui.QGridLayout(self.scrollAreaWidgetContents_4_2)
        self.gridLayout_49.setObjectName(_fromUtf8("gridLayout_49"))
        self.scrollArea_4_2.setWidget(self.scrollAreaWidgetContents_4_2)
        self.gridLayout_47.addWidget(self.scrollArea_4_2, 3, 0, 1, 5)
        self.toolButton_4_2 = QtGui.QToolButton(self.groupBox_4_2)
        self.toolButton_4_2.setIcon(icon1)
        self.toolButton_4_2.setObjectName(_fromUtf8("toolButton_4_2"))
        self.gridLayout_47.addWidget(self.toolButton_4_2, 2, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.groupBox_4_2)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_47.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_4_2)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_47.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.toolButton_4_1 = QtGui.QToolButton(self.groupBox_4_2)
        self.toolButton_4_1.setIcon(icon1)
        self.toolButton_4_1.setObjectName(_fromUtf8("toolButton_4_1"))
        self.gridLayout_47.addWidget(self.toolButton_4_1, 0, 1, 1, 1)
        self.toolButton_4_3 = QtGui.QToolButton(self.groupBox_4_2)
        self.toolButton_4_3.setIcon(icon)
        self.toolButton_4_3.setObjectName(_fromUtf8("toolButton_4_3"))
        self.gridLayout_47.addWidget(self.toolButton_4_3, 0, 3, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_47.addItem(spacerItem15, 0, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_47.addItem(spacerItem16, 4, 1, 1, 1)
        self.gridLayout_46.addWidget(self.groupBox_4_2, 0, 0, 1, 1)
        self.gridLayout_45.addWidget(self.groupBox_4_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_50 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_50.setObjectName(_fromUtf8("gridLayout_50"))
        self.groupBox_5_1 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5_1.setObjectName(_fromUtf8("groupBox_5_1"))
        self.gridLayout_51 = QtGui.QGridLayout(self.groupBox_5_1)
        self.gridLayout_51.setObjectName(_fromUtf8("gridLayout_51"))
        self.groupBox_5_2 = QtGui.QGroupBox(self.groupBox_5_1)
        self.groupBox_5_2.setObjectName(_fromUtf8("groupBox_5_2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_5_2)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.lineEdit_5_3 = QtGui.QLineEdit(self.groupBox_5_2)
        self.lineEdit_5_3.setObjectName(_fromUtf8("lineEdit_5_3"))
        self.gridLayout_13.addWidget(self.lineEdit_5_3, 4, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_5_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_13.addWidget(self.label_9, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_5_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_13.addWidget(self.label, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_5_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_13.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_5_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_13.addWidget(self.label_12, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_5_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_13.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_5_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_13.addWidget(self.label_3, 1, 2, 1, 1)
        self.lineEdit_5_1 = QtGui.QLineEdit(self.groupBox_5_2)
        self.lineEdit_5_1.setObjectName(_fromUtf8("lineEdit_5_1"))
        self.gridLayout_13.addWidget(self.lineEdit_5_1, 4, 0, 1, 1)
        self.lineEdit_5_4 = QtGui.QLineEdit(self.groupBox_5_2)
        self.lineEdit_5_4.setObjectName(_fromUtf8("lineEdit_5_4"))
        self.gridLayout_13.addWidget(self.lineEdit_5_4, 4, 3, 1, 1)
        self.lineEdit_5_2 = QtGui.QLineEdit(self.groupBox_5_2)
        self.lineEdit_5_2.setObjectName(_fromUtf8("lineEdit_5_2"))
        self.gridLayout_13.addWidget(self.lineEdit_5_2, 4, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_5_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_13.addWidget(self.label_11, 3, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_5_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_13.addWidget(self.label_5, 2, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem17, 5, 0, 1, 1)
        self.pushButton_5_1 = QtGui.QPushButton(self.groupBox_5_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Metadata_editor/icons/location.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5_1.setIcon(icon3)
        self.pushButton_5_1.setObjectName(_fromUtf8("pushButton_5_1"))
        self.gridLayout_13.addWidget(self.pushButton_5_1, 6, 0, 1, 2)
        self.toolButton_5_1 = QtGui.QToolButton(self.groupBox_5_2)
        self.toolButton_5_1.setIcon(icon)
        self.toolButton_5_1.setObjectName(_fromUtf8("toolButton_5_1"))
        self.gridLayout_13.addWidget(self.toolButton_5_1, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_5_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_13.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_5_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_13.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_5_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_13.addWidget(self.label_8, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_5_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_13.addWidget(self.label_7, 2, 2, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem18, 7, 0, 1, 1)
        self.pushButton_5_2 = QtGui.QPushButton(self.groupBox_5_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Metadata_editor/icons/select_red.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5_2.setIcon(icon4)
        self.pushButton_5_2.setObjectName(_fromUtf8("pushButton_5_2"))
        self.gridLayout_13.addWidget(self.pushButton_5_2, 6, 2, 1, 2)
        self.gridLayout_51.addWidget(self.groupBox_5_2, 0, 0, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_51.addItem(spacerItem19, 0, 1, 1, 1)
        self.toolButton_5_2 = QtGui.QToolButton(self.groupBox_5_1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Metadata_editor/icons/ZoomOut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5_2.setIcon(icon5)
        self.toolButton_5_2.setObjectName(_fromUtf8("toolButton_5_2"))
        self.gridLayout_51.addWidget(self.toolButton_5_2, 2, 1, 1, 1)
        self.toolButton_5_3 = QtGui.QToolButton(self.groupBox_5_1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Metadata_editor/icons/ZoomIn.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5_3.setIcon(icon6)
        self.toolButton_5_3.setObjectName(_fromUtf8("toolButton_5_3"))
        self.gridLayout_51.addWidget(self.toolButton_5_3, 1, 1, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_51.addItem(spacerItem20, 4, 1, 1, 1)
        self.widget = QtGui.QWidget(self.groupBox_5_1)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_51.addWidget(self.widget, 1, 0, 4, 1)
        self.toolButton_5_4 = QtGui.QToolButton(self.groupBox_5_1)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Metadata_editor/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5_4.setIcon(icon7)
        self.toolButton_5_4.setObjectName(_fromUtf8("toolButton_5_4"))
        self.gridLayout_51.addWidget(self.toolButton_5_4, 3, 1, 1, 1)
        self.gridLayout_50.addWidget(self.groupBox_5_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.groupBox_6_1 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_6_1.setObjectName(_fromUtf8("groupBox_6_1"))
        self.gridLayout_52 = QtGui.QGridLayout(self.groupBox_6_1)
        self.gridLayout_52.setObjectName(_fromUtf8("gridLayout_52"))
        self.groupBox_6_2 = QtGui.QGroupBox(self.groupBox_6_1)
        self.groupBox_6_2.setCheckable(True)
        self.groupBox_6_2.setChecked(False)
        self.groupBox_6_2.setObjectName(_fromUtf8("groupBox_6_2"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_6_2)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.dateEdit_6_1 = QtGui.QDateEdit(self.groupBox_6_2)
        self.dateEdit_6_1.setCalendarPopup(True)
        self.dateEdit_6_1.setObjectName(_fromUtf8("dateEdit_6_1"))
        self.gridLayout_17.addWidget(self.dateEdit_6_1, 0, 0, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(466, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem21, 0, 1, 1, 1)
        self.toolButton_6_1 = QtGui.QToolButton(self.groupBox_6_2)
        self.toolButton_6_1.setIcon(icon)
        self.toolButton_6_1.setObjectName(_fromUtf8("toolButton_6_1"))
        self.gridLayout_17.addWidget(self.toolButton_6_1, 0, 2, 1, 1)
        self.gridLayout_52.addWidget(self.groupBox_6_2, 2, 0, 1, 1)
        self.groupBox_6_3 = QtGui.QGroupBox(self.groupBox_6_1)
        self.groupBox_6_3.setCheckable(True)
        self.groupBox_6_3.setChecked(False)
        self.groupBox_6_3.setObjectName(_fromUtf8("groupBox_6_3"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_6_3)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.dateEdit_6_2 = QtGui.QDateEdit(self.groupBox_6_3)
        self.dateEdit_6_2.setCalendarPopup(True)
        self.dateEdit_6_2.setObjectName(_fromUtf8("dateEdit_6_2"))
        self.gridLayout_16.addWidget(self.dateEdit_6_2, 0, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(466, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem22, 0, 1, 1, 1)
        self.toolButton_6_2 = QtGui.QToolButton(self.groupBox_6_3)
        self.toolButton_6_2.setIcon(icon)
        self.toolButton_6_2.setObjectName(_fromUtf8("toolButton_6_2"))
        self.gridLayout_16.addWidget(self.toolButton_6_2, 0, 2, 1, 1)
        self.gridLayout_52.addWidget(self.groupBox_6_3, 3, 0, 1, 1)
        self.groupBox_6_4 = QtGui.QGroupBox(self.groupBox_6_1)
        self.groupBox_6_4.setCheckable(True)
        self.groupBox_6_4.setChecked(False)
        self.groupBox_6_4.setObjectName(_fromUtf8("groupBox_6_4"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_6_4)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.dateEdit_6_3 = QtGui.QDateEdit(self.groupBox_6_4)
        self.dateEdit_6_3.setCalendarPopup(True)
        self.dateEdit_6_3.setObjectName(_fromUtf8("dateEdit_6_3"))
        self.gridLayout_18.addWidget(self.dateEdit_6_3, 0, 0, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(466, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem23, 0, 1, 1, 1)
        self.toolButton_6_3 = QtGui.QToolButton(self.groupBox_6_4)
        self.toolButton_6_3.setIcon(icon)
        self.toolButton_6_3.setObjectName(_fromUtf8("toolButton_6_3"))
        self.gridLayout_18.addWidget(self.toolButton_6_3, 0, 2, 1, 1)
        self.gridLayout_52.addWidget(self.groupBox_6_4, 4, 0, 1, 1)
        self.groupBox_6_5 = QtGui.QGroupBox(self.groupBox_6_1)
        self.groupBox_6_5.setCheckable(True)
        self.groupBox_6_5.setChecked(False)
        self.groupBox_6_5.setObjectName(_fromUtf8("groupBox_6_5"))
        self.gridLayout_53 = QtGui.QGridLayout(self.groupBox_6_5)
        self.gridLayout_53.setObjectName(_fromUtf8("gridLayout_53"))
        self.groupBox_6_6 = QtGui.QGroupBox(self.groupBox_6_5)
        self.groupBox_6_6.setObjectName(_fromUtf8("groupBox_6_6"))
        self.gridLayout_54 = QtGui.QGridLayout(self.groupBox_6_6)
        self.gridLayout_54.setObjectName(_fromUtf8("gridLayout_54"))
        spacerItem24 = QtGui.QSpacerItem(219, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_54.addItem(spacerItem24, 0, 1, 1, 1)
        self.dateEdit_6_4 = QtGui.QDateEdit(self.groupBox_6_6)
        self.dateEdit_6_4.setCalendarPopup(True)
        self.dateEdit_6_4.setObjectName(_fromUtf8("dateEdit_6_4"))
        self.gridLayout_54.addWidget(self.dateEdit_6_4, 0, 0, 1, 1)
        self.gridLayout_53.addWidget(self.groupBox_6_6, 2, 0, 1, 1)
        self.groupBox_6_7 = QtGui.QGroupBox(self.groupBox_6_5)
        self.groupBox_6_7.setObjectName(_fromUtf8("groupBox_6_7"))
        self.gridLayout_55 = QtGui.QGridLayout(self.groupBox_6_7)
        self.gridLayout_55.setObjectName(_fromUtf8("gridLayout_55"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_6_7)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_55.addWidget(self.radioButton, 1, 0, 1, 1)
        self.dateEdit_6 = QtGui.QDateEdit(self.groupBox_6_7)
        self.dateEdit_6.setCalendarPopup(True)
        self.dateEdit_6.setObjectName(_fromUtf8("dateEdit_6"))
        self.gridLayout_55.addWidget(self.dateEdit_6, 3, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_6_7)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_55.addWidget(self.radioButton_2, 2, 0, 1, 1)
        self.gridLayout_53.addWidget(self.groupBox_6_7, 2, 1, 1, 1)
        self.toolButton_6_4 = QtGui.QToolButton(self.groupBox_6_5)
        self.toolButton_6_4.setIcon(icon)
        self.toolButton_6_4.setObjectName(_fromUtf8("toolButton_6_4"))
        self.gridLayout_53.addWidget(self.toolButton_6_4, 0, 3, 1, 1)
        self.gridLayout_52.addWidget(self.groupBox_6_5, 0, 0, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_52.addItem(spacerItem25, 5, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_6_1, 0, 0, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem26, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_56 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_56.setObjectName(_fromUtf8("gridLayout_56"))
        self.groupBox_7_1 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_7_1.setObjectName(_fromUtf8("groupBox_7_1"))
        self.gridLayout_57 = QtGui.QGridLayout(self.groupBox_7_1)
        self.gridLayout_57.setObjectName(_fromUtf8("gridLayout_57"))
        self.groupBox_7_3 = QtGui.QGroupBox(self.groupBox_7_1)
        self.groupBox_7_3.setObjectName(_fromUtf8("groupBox_7_3"))
        self.gridLayout_59 = QtGui.QGridLayout(self.groupBox_7_3)
        self.gridLayout_59.setObjectName(_fromUtf8("gridLayout_59"))
        self.radioButton_7_1 = QtGui.QRadioButton(self.groupBox_7_3)
        self.radioButton_7_1.setChecked(True)
        self.radioButton_7_1.setObjectName(_fromUtf8("radioButton_7_1"))
        self.gridLayout_59.addWidget(self.radioButton_7_1, 2, 0, 1, 1)
        self.toolButton_7_2 = QtGui.QToolButton(self.groupBox_7_3)
        self.toolButton_7_2.setIcon(icon)
        self.toolButton_7_2.setObjectName(_fromUtf8("toolButton_7_2"))
        self.gridLayout_59.addWidget(self.toolButton_7_2, 0, 4, 1, 1)
        self.radioButton_7_2 = QtGui.QRadioButton(self.groupBox_7_3)
        self.radioButton_7_2.setObjectName(_fromUtf8("radioButton_7_2"))
        self.gridLayout_59.addWidget(self.radioButton_7_2, 3, 0, 1, 1)
        self.spinBox_7_1 = QtGui.QSpinBox(self.groupBox_7_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_7_1.sizePolicy().hasHeightForWidth())
        self.spinBox_7_1.setSizePolicy(sizePolicy)
        self.spinBox_7_1.setMinimum(0)
        self.spinBox_7_1.setMaximum(10000000)
        self.spinBox_7_1.setSingleStep(1000)
        self.spinBox_7_1.setProperty("value", 0)
        self.spinBox_7_1.setObjectName(_fromUtf8("spinBox_7_1"))
        self.gridLayout_59.addWidget(self.spinBox_7_1, 2, 2, 1, 1)
        self.comboBox_7_1 = QtGui.QComboBox(self.groupBox_7_3)
        self.comboBox_7_1.setObjectName(_fromUtf8("comboBox_7_1"))
        self.comboBox_7_1.addItem(_fromUtf8(""))
        self.comboBox_7_1.addItem(_fromUtf8(""))
        self.comboBox_7_1.addItem(_fromUtf8(""))
        self.gridLayout_59.addWidget(self.comboBox_7_1, 3, 3, 1, 1)
        self.doubleSpinBox_7_1 = QtGui.QDoubleSpinBox(self.groupBox_7_3)
        self.doubleSpinBox_7_1.setMaximum(1000.0)
        self.doubleSpinBox_7_1.setSingleStep(10.0)
        self.doubleSpinBox_7_1.setProperty("value", 0.0)
        self.doubleSpinBox_7_1.setObjectName(_fromUtf8("doubleSpinBox_7_1"))
        self.gridLayout_59.addWidget(self.doubleSpinBox_7_1, 3, 2, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_59.addItem(spacerItem27, 0, 5, 1, 1)
        self.gridLayout_57.addWidget(self.groupBox_7_3, 1, 0, 1, 1)
        self.groupBox_7_2 = QtGui.QGroupBox(self.groupBox_7_1)
        self.groupBox_7_2.setObjectName(_fromUtf8("groupBox_7_2"))
        self.gridLayout_58 = QtGui.QGridLayout(self.groupBox_7_2)
        self.gridLayout_58.setObjectName(_fromUtf8("gridLayout_58"))
        self.toolButton_7_1 = QtGui.QToolButton(self.groupBox_7_2)
        self.toolButton_7_1.setIcon(icon)
        self.toolButton_7_1.setObjectName(_fromUtf8("toolButton_7_1"))
        self.gridLayout_58.addWidget(self.toolButton_7_1, 0, 1, 1, 1)
        self.textEdit_7_1 = QtGui.QTextEdit(self.groupBox_7_2)
        self.textEdit_7_1.setObjectName(_fromUtf8("textEdit_7_1"))
        self.gridLayout_58.addWidget(self.textEdit_7_1, 1, 0, 2, 1)
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_58.addItem(spacerItem28, 3, 0, 1, 1)
        self.gridLayout_57.addWidget(self.groupBox_7_2, 0, 0, 1, 1)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_57.addItem(spacerItem29, 2, 0, 1, 1)
        self.gridLayout_56.addWidget(self.groupBox_7_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_60 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_60.setObjectName(_fromUtf8("gridLayout_60"))
        self.groupBox_8_1 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_8_1.setObjectName(_fromUtf8("groupBox_8_1"))
        self.gridLayout_61 = QtGui.QGridLayout(self.groupBox_8_1)
        self.gridLayout_61.setObjectName(_fromUtf8("gridLayout_61"))
        self.groupBox_8_2 = QtGui.QGroupBox(self.groupBox_8_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8_2.sizePolicy().hasHeightForWidth())
        self.groupBox_8_2.setSizePolicy(sizePolicy)
        self.groupBox_8_2.setMinimumSize(QtCore.QSize(0, 410))
        self.groupBox_8_2.setCheckable(True)
        self.groupBox_8_2.setChecked(False)
        self.groupBox_8_2.setObjectName(_fromUtf8("groupBox_8_2"))
        self.gridLayout_63 = QtGui.QGridLayout(self.groupBox_8_2)
        self.gridLayout_63.setObjectName(_fromUtf8("gridLayout_63"))
        self.scrollArea_8_1 = QtGui.QScrollArea(self.groupBox_8_2)
        self.scrollArea_8_1.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_8_1.setWidgetResizable(True)
        self.scrollArea_8_1.setObjectName(_fromUtf8("scrollArea_8_1"))
        self.scrollAreaWidgetContents_8_1 = QtGui.QWidget()
        self.scrollAreaWidgetContents_8_1.setGeometry(QtCore.QRect(0, 0, 550, 331))
        self.scrollAreaWidgetContents_8_1.setObjectName(_fromUtf8("scrollAreaWidgetContents_8_1"))
        self.gridLayout_68 = QtGui.QGridLayout(self.scrollAreaWidgetContents_8_1)
        self.gridLayout_68.setObjectName(_fromUtf8("gridLayout_68"))
        self.groupBox_8_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents_8_1)
        self.groupBox_8_5.setObjectName(_fromUtf8("groupBox_8_5"))
        self.gridLayout_66 = QtGui.QGridLayout(self.groupBox_8_5)
        self.gridLayout_66.setObjectName(_fromUtf8("gridLayout_66"))
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_66.addItem(spacerItem30, 0, 1, 1, 1)
        self.comboBox_8_2 = QtGui.QComboBox(self.groupBox_8_5)
        self.comboBox_8_2.setObjectName(_fromUtf8("comboBox_8_2"))
        self.comboBox_8_2.addItem(_fromUtf8(""))
        self.comboBox_8_2.addItem(_fromUtf8(""))
        self.comboBox_8_2.addItem(_fromUtf8(""))
        self.gridLayout_66.addWidget(self.comboBox_8_2, 0, 0, 1, 1)
        self.gridLayout_68.addWidget(self.groupBox_8_5, 1, 1, 1, 1)
        self.groupBox_8_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_8_1)
        self.groupBox_8_4.setObjectName(_fromUtf8("groupBox_8_4"))
        self.gridLayout_67 = QtGui.QGridLayout(self.groupBox_8_4)
        self.gridLayout_67.setObjectName(_fromUtf8("gridLayout_67"))
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_67.addItem(spacerItem31, 0, 1, 1, 1)
        self.dateEdit_8_1 = QtGui.QDateEdit(self.groupBox_8_4)
        self.dateEdit_8_1.setCalendarPopup(True)
        self.dateEdit_8_1.setObjectName(_fromUtf8("dateEdit_8_1"))
        self.gridLayout_67.addWidget(self.dateEdit_8_1, 0, 0, 1, 1)
        self.gridLayout_68.addWidget(self.groupBox_8_4, 1, 0, 1, 1)
        self.groupBox_8_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents_8_1)
        self.groupBox_8_6.setObjectName(_fromUtf8("groupBox_8_6"))
        self.gridLayout_65 = QtGui.QGridLayout(self.groupBox_8_6)
        self.gridLayout_65.setObjectName(_fromUtf8("gridLayout_65"))
        self.comboBox_8_3 = QtGui.QComboBox(self.groupBox_8_6)
        self.comboBox_8_3.setObjectName(_fromUtf8("comboBox_8_3"))
        self.comboBox_8_3.addItem(_fromUtf8(""))
        self.comboBox_8_3.addItem(_fromUtf8(""))
        self.comboBox_8_3.addItem(_fromUtf8(""))
        self.gridLayout_65.addWidget(self.comboBox_8_3, 0, 0, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_65.addItem(spacerItem32, 0, 1, 1, 1)
        self.gridLayout_68.addWidget(self.groupBox_8_6, 2, 0, 1, 1)
        self.groupBox_8_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_8_1)
        self.groupBox_8_3.setObjectName(_fromUtf8("groupBox_8_3"))
        self.gridLayout_62 = QtGui.QGridLayout(self.groupBox_8_3)
        self.gridLayout_62.setObjectName(_fromUtf8("gridLayout_62"))
        self.lineEdit_8_1 = QtGui.QLineEdit(self.groupBox_8_3)
        self.lineEdit_8_1.setObjectName(_fromUtf8("lineEdit_8_1"))
        self.gridLayout_62.addWidget(self.lineEdit_8_1, 0, 0, 1, 1)
        self.checkBox_8_1 = QtGui.QCheckBox(self.groupBox_8_3)
        self.checkBox_8_1.setObjectName(_fromUtf8("checkBox_8_1"))
        self.gridLayout_62.addWidget(self.checkBox_8_1, 1, 0, 1, 1)
        self.listWidget_8_1 = QtGui.QListWidget(self.groupBox_8_3)
        self.listWidget_8_1.setObjectName(_fromUtf8("listWidget_8_1"))
        self.gridLayout_62.addWidget(self.listWidget_8_1, 2, 0, 1, 1)
        self.gridLayout_68.addWidget(self.groupBox_8_3, 0, 0, 1, 3)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_68.addItem(spacerItem33, 1, 2, 1, 1)
        self.scrollArea_8_1.setWidget(self.scrollAreaWidgetContents_8_1)
        self.gridLayout_63.addWidget(self.scrollArea_8_1, 0, 0, 1, 1)
        self.gridLayout_61.addWidget(self.groupBox_8_2, 1, 0, 1, 1)
        self.toolButton_8_1 = QtGui.QToolButton(self.groupBox_8_1)
        self.toolButton_8_1.setIcon(icon)
        self.toolButton_8_1.setObjectName(_fromUtf8("toolButton_8_1"))
        self.gridLayout_61.addWidget(self.toolButton_8_1, 0, 1, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_61.addItem(spacerItem34, 2, 0, 1, 1)
        self.gridLayout_60.addWidget(self.groupBox_8_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.gridLayout_69 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_69.setObjectName(_fromUtf8("gridLayout_69"))
        spacerItem35 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_69.addItem(spacerItem35, 1, 0, 1, 1)
        self.groupBox_9_1 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_9_1.setObjectName(_fromUtf8("groupBox_9_1"))
        self.gridLayout_70 = QtGui.QGridLayout(self.groupBox_9_1)
        self.gridLayout_70.setObjectName(_fromUtf8("gridLayout_70"))
        self.scrollArea_9_1 = QtGui.QScrollArea(self.groupBox_9_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_9_1.sizePolicy().hasHeightForWidth())
        self.scrollArea_9_1.setSizePolicy(sizePolicy)
        self.scrollArea_9_1.setWidgetResizable(True)
        self.scrollArea_9_1.setObjectName(_fromUtf8("scrollArea_9_1"))
        self.scrollAreaWidgetContents_9_1 = QtGui.QWidget()
        self.scrollAreaWidgetContents_9_1.setGeometry(QtCore.QRect(0, 0, 419, 204))
        self.scrollAreaWidgetContents_9_1.setObjectName(_fromUtf8("scrollAreaWidgetContents_9_1"))
        self.gridLayout_71 = QtGui.QGridLayout(self.scrollAreaWidgetContents_9_1)
        self.gridLayout_71.setObjectName(_fromUtf8("gridLayout_71"))
        spacerItem36 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_71.addItem(spacerItem36, 8, 1, 1, 1)
        self.groupBox_9_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_9_1)
        self.groupBox_9_3.setObjectName(_fromUtf8("groupBox_9_3"))
        self.gridLayout_73 = QtGui.QGridLayout(self.groupBox_9_3)
        self.gridLayout_73.setObjectName(_fromUtf8("gridLayout_73"))
        self.comboBox_9_2 = QtGui.QComboBox(self.groupBox_9_3)
        self.comboBox_9_2.setEditable(True)
        self.comboBox_9_2.setObjectName(_fromUtf8("comboBox_9_2"))
        self.gridLayout_73.addWidget(self.comboBox_9_2, 0, 0, 1, 1)
        spacerItem37 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_73.addItem(spacerItem37, 0, 1, 1, 1)
        self.gridLayout_71.addWidget(self.groupBox_9_3, 5, 0, 4, 1)
        self.toolButton_9_2 = QtGui.QToolButton(self.scrollAreaWidgetContents_9_1)
        self.toolButton_9_2.setIcon(icon1)
        self.toolButton_9_2.setObjectName(_fromUtf8("toolButton_9_2"))
        self.gridLayout_71.addWidget(self.toolButton_9_2, 3, 1, 1, 1)
        self.groupBox_9_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_9_1)
        self.groupBox_9_2.setObjectName(_fromUtf8("groupBox_9_2"))
        self.gridLayout_72 = QtGui.QGridLayout(self.groupBox_9_2)
        self.gridLayout_72.setObjectName(_fromUtf8("gridLayout_72"))
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_72.addItem(spacerItem38, 0, 1, 1, 1)
        self.comboBox_9_1 = QtGui.QComboBox(self.groupBox_9_2)
        self.comboBox_9_1.setEditable(True)
        self.comboBox_9_1.setObjectName(_fromUtf8("comboBox_9_1"))
        self.gridLayout_72.addWidget(self.comboBox_9_1, 0, 0, 1, 1)
        self.gridLayout_71.addWidget(self.groupBox_9_2, 1, 0, 4, 1)
        spacerItem39 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_71.addItem(spacerItem39, 4, 1, 1, 1)
        self.toolButton_9_1 = QtGui.QToolButton(self.scrollAreaWidgetContents_9_1)
        self.toolButton_9_1.setIcon(icon2)
        self.toolButton_9_1.setObjectName(_fromUtf8("toolButton_9_1"))
        self.gridLayout_71.addWidget(self.toolButton_9_1, 2, 1, 1, 1)
        self.toolButton_9_5 = QtGui.QToolButton(self.scrollAreaWidgetContents_9_1)
        self.toolButton_9_5.setIcon(icon)
        self.toolButton_9_5.setObjectName(_fromUtf8("toolButton_9_5"))
        self.gridLayout_71.addWidget(self.toolButton_9_5, 1, 1, 1, 1)
        self.toolButton_9_6 = QtGui.QToolButton(self.scrollAreaWidgetContents_9_1)
        self.toolButton_9_6.setIcon(icon)
        self.toolButton_9_6.setObjectName(_fromUtf8("toolButton_9_6"))
        self.gridLayout_71.addWidget(self.toolButton_9_6, 5, 1, 1, 1)
        self.toolButton_9_3 = QtGui.QToolButton(self.scrollAreaWidgetContents_9_1)
        self.toolButton_9_3.setIcon(icon2)
        self.toolButton_9_3.setObjectName(_fromUtf8("toolButton_9_3"))
        self.gridLayout_71.addWidget(self.toolButton_9_3, 6, 1, 1, 1)
        self.toolButton_9_4 = QtGui.QToolButton(self.scrollAreaWidgetContents_9_1)
        self.toolButton_9_4.setIcon(icon1)
        self.toolButton_9_4.setObjectName(_fromUtf8("toolButton_9_4"))
        self.gridLayout_71.addWidget(self.toolButton_9_4, 7, 1, 1, 1)
        self.scrollArea_9_1.setWidget(self.scrollAreaWidgetContents_9_1)
        self.gridLayout_70.addWidget(self.scrollArea_9_1, 2, 0, 1, 1)
        self.gridLayout_69.addWidget(self.groupBox_9_1, 0, 0, 1, 1)
        spacerItem40 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_69.addItem(spacerItem40, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.gridLayout_74 = QtGui.QGridLayout(self.tab_10)
        self.gridLayout_74.setObjectName(_fromUtf8("gridLayout_74"))
        self.groupBox_10_1 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_10_1.setObjectName(_fromUtf8("groupBox_10_1"))
        self.gridLayout_75 = QtGui.QGridLayout(self.groupBox_10_1)
        self.gridLayout_75.setObjectName(_fromUtf8("gridLayout_75"))
        self.label_10_2 = QtGui.QLabel(self.groupBox_10_1)
        self.label_10_2.setObjectName(_fromUtf8("label_10_2"))
        self.gridLayout_75.addWidget(self.label_10_2, 1, 0, 1, 1)
        self.scrollArea_10_1 = QtGui.QScrollArea(self.groupBox_10_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_10_1.sizePolicy().hasHeightForWidth())
        self.scrollArea_10_1.setSizePolicy(sizePolicy)
        self.scrollArea_10_1.setMinimumSize(QtCore.QSize(0, 380))
        self.scrollArea_10_1.setWidgetResizable(True)
        self.scrollArea_10_1.setObjectName(_fromUtf8("scrollArea_10_1"))
        self.scrollAreaWidgetContents_10_1 = QtGui.QWidget()
        self.scrollAreaWidgetContents_10_1.setGeometry(QtCore.QRect(0, 0, 358, 451))
        self.scrollAreaWidgetContents_10_1.setObjectName(_fromUtf8("scrollAreaWidgetContents_10_1"))
        self.gridLayout_76 = QtGui.QGridLayout(self.scrollAreaWidgetContents_10_1)
        self.gridLayout_76.setObjectName(_fromUtf8("gridLayout_76"))
        self.toolButton_10_3 = QtGui.QToolButton(self.scrollAreaWidgetContents_10_1)
        self.toolButton_10_3.setIcon(icon2)
        self.toolButton_10_3.setObjectName(_fromUtf8("toolButton_10_3"))
        self.gridLayout_76.addWidget(self.toolButton_10_3, 0, 2, 1, 1)
        self.groupBox_10_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_10_1)
        self.groupBox_10_2.setObjectName(_fromUtf8("groupBox_10_2"))
        self.gridLayout_77 = QtGui.QGridLayout(self.groupBox_10_2)
        self.gridLayout_77.setObjectName(_fromUtf8("gridLayout_77"))
        self.groupBox_10_5 = QtGui.QGroupBox(self.groupBox_10_2)
        self.groupBox_10_5.setObjectName(_fromUtf8("groupBox_10_5"))
        self.gridLayout_78 = QtGui.QGridLayout(self.groupBox_10_5)
        self.gridLayout_78.setObjectName(_fromUtf8("gridLayout_78"))
        self.comboBox_10_1 = QtGui.QComboBox(self.groupBox_10_5)
        self.comboBox_10_1.setObjectName(_fromUtf8("comboBox_10_1"))
        self.gridLayout_78.addWidget(self.comboBox_10_1, 0, 0, 1, 1)
        spacerItem41 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_78.addItem(spacerItem41, 0, 1, 1, 1)
        self.gridLayout_77.addWidget(self.groupBox_10_5, 2, 0, 1, 1)
        self.groupBox_10_4 = QtGui.QGroupBox(self.groupBox_10_2)
        self.groupBox_10_4.setObjectName(_fromUtf8("groupBox_10_4"))
        self.gridLayout_79 = QtGui.QGridLayout(self.groupBox_10_4)
        self.gridLayout_79.setObjectName(_fromUtf8("gridLayout_79"))
        self.lineEdit_10_2 = QtGui.QLineEdit(self.groupBox_10_4)
        self.lineEdit_10_2.setObjectName(_fromUtf8("lineEdit_10_2"))
        self.gridLayout_79.addWidget(self.lineEdit_10_2, 0, 0, 1, 1)
        self.gridLayout_77.addWidget(self.groupBox_10_4, 1, 0, 1, 1)
        self.groupBox_10_3 = QtGui.QGroupBox(self.groupBox_10_2)
        self.groupBox_10_3.setObjectName(_fromUtf8("groupBox_10_3"))
        self.gridLayout_80 = QtGui.QGridLayout(self.groupBox_10_3)
        self.gridLayout_80.setObjectName(_fromUtf8("gridLayout_80"))
        self.lineEdit_10_1 = QtGui.QLineEdit(self.groupBox_10_3)
        self.lineEdit_10_1.setObjectName(_fromUtf8("lineEdit_10_1"))
        self.gridLayout_80.addWidget(self.lineEdit_10_1, 1, 0, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.groupBox_10_3)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout_80.addWidget(self.checkBox_10, 2, 0, 1, 1)
        self.gridLayout_77.addWidget(self.groupBox_10_3, 0, 0, 1, 1)
        self.groupBox_10_6 = QtGui.QGroupBox(self.groupBox_10_2)
        self.groupBox_10_6.setObjectName(_fromUtf8("groupBox_10_6"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_10_6)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.lineEdit_10_3 = QtGui.QLineEdit(self.groupBox_10_6)
        self.lineEdit_10_3.setObjectName(_fromUtf8("lineEdit_10_3"))
        self.gridLayout_19.addWidget(self.lineEdit_10_3, 0, 0, 1, 1)
        self.gridLayout_77.addWidget(self.groupBox_10_6, 3, 0, 1, 1)
        self.groupBox_10_7 = QtGui.QGroupBox(self.groupBox_10_2)
        self.groupBox_10_7.setObjectName(_fromUtf8("groupBox_10_7"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_10_7)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.lineEdit_10_4 = QtGui.QLineEdit(self.groupBox_10_7)
        self.lineEdit_10_4.setObjectName(_fromUtf8("lineEdit_10_4"))
        self.gridLayout_20.addWidget(self.lineEdit_10_4, 0, 0, 1, 1)
        self.gridLayout_77.addWidget(self.groupBox_10_7, 4, 0, 1, 1)
        self.gridLayout_76.addWidget(self.groupBox_10_2, 1, 0, 1, 1)
        self.toolButton_10_5 = QtGui.QToolButton(self.scrollAreaWidgetContents_10_1)
        self.toolButton_10_5.setIcon(icon1)
        self.toolButton_10_5.setObjectName(_fromUtf8("toolButton_10_5"))
        self.gridLayout_76.addWidget(self.toolButton_10_5, 0, 3, 1, 1)
        self.toolButton_10_4 = QtGui.QToolButton(self.scrollAreaWidgetContents_10_1)
        self.toolButton_10_4.setIcon(icon)
        self.toolButton_10_4.setObjectName(_fromUtf8("toolButton_10_4"))
        self.gridLayout_76.addWidget(self.toolButton_10_4, 0, 1, 1, 1)
        self.scrollArea_10_1.setWidget(self.scrollAreaWidgetContents_10_1)
        self.gridLayout_75.addWidget(self.scrollArea_10_1, 2, 0, 1, 1)
        self.label_10_1 = QtGui.QLabel(self.groupBox_10_1)
        self.label_10_1.setObjectName(_fromUtf8("label_10_1"))
        self.gridLayout_75.addWidget(self.label_10_1, 0, 0, 1, 1)
        self.listWidget_2 = QtGui.QListWidget(self.groupBox_10_1)
        self.listWidget_2.setMinimumSize(QtCore.QSize(380, 0))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.gridLayout_75.addWidget(self.listWidget_2, 2, 1, 1, 1)
        spacerItem42 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_75.addItem(spacerItem42, 2, 2, 1, 1)
        self.gridLayout_74.addWidget(self.groupBox_10_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_10, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 5)
        spacerItem43 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem43, 1, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Editor)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.NoButton)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 3, 1, 1)
        self.label_13 = QtGui.QLabel(Editor)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 1, 1, 1)

        self.retranslateUi(Editor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dateEdit_6.setEnabled)
        QtCore.QObject.connect(self.radioButton_7_1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBox_7_1.setEnabled)
        QtCore.QObject.connect(self.radioButton_7_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_7_1.setEnabled)
        QtCore.QObject.connect(self.radioButton_7_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBox_7_1.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.listWidget.setVisible)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), self.checkBox.click)
        QtCore.QObject.connect(self.checkBox_10, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.listWidget_2.setVisible)
        QtCore.QObject.connect(self.listWidget_8_1, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), self.checkBox_8_1.click)
        QtCore.QObject.connect(self.checkBox_8_1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.listWidget_8_1.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Editor)

    def retranslateUi(self, Editor):
        Editor.setWindowTitle(_translate("Editor", "Μεταδεδομένα", None))
        self.groupBox.setTitle(_translate("Editor", "ΜΕΤΑΔΕΔΟΜΕΝΑ ΣΧΕΤΙΚΑ ΜΕ ΜΕΤΑΔΕΔΟΜΕΝΑ", None))
        self.groupBox_4.setTitle(_translate("Editor", "Γλώσσα μεταδεδομένων (*)", None))
        self.toolButton_5.setText(_translate("Editor", " i ", None))
        self.groupBox_2.setTitle(_translate("Editor", "Αρμόδιος για επικοινωνία σχετικά με τα μεταδεδομένα (*)", None))
        self.toolButton.setText(_translate("Editor", " i ", None))
        self.groupBox_5.setTitle(_translate("Editor", "Αρμόδιος για επικοινωνία", None))
        self.groupBox_6.setTitle(_translate("Editor", "Ιστότοπος (Προαιρετικό)", None))
        self.groupBox_8.setTitle(_translate("Editor", "Ηλεκτρονική διεύθυνση (*)", None))
        self.groupBox_7.setTitle(_translate("Editor", "Oνομασία του οργανισμού (*)", None))
        self.checkBox.setText(_translate("Editor", "Επιλογή από λίστα", None))
        self.groupBox_9.setTitle(_translate("Editor", "Τηλέφωνο (Προαιρετικό)", None))
        self.groupBox_3.setTitle(_translate("Editor", "Ημερομηνία μεταδεδομένων", None))
        self.dateEdit.setDisplayFormat(_translate("Editor", "d/M/yyyy", None))
        self.toolButton_4.setText(_translate("Editor", " i ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Editor", "Μεταδεδομένα", None))
        self.groupBox_2_1.setTitle(_translate("Editor", "ΤΑΥΤΟΠΟΙΗΣΗ", None))
        self.groupBox_2_2.setTitle(_translate("Editor", "Τίτλος γεωγραφικών δεδομένων (*)", None))
        self.toolButton_2_1.setText(_translate("Editor", " i ", None))
        self.groupBox_2_4.setTitle(_translate("Editor", "Σύνοψη γεωγραφικών δεδομένων (*)", None))
        self.toolButton_2_5.setText(_translate("Editor", " i ", None))
        self.groupBox_2_3.setTitle(_translate("Editor", "Αναγνωριστικό (*)", None))
        self.toolButton_2_4.setText(_translate("Editor", " i ", None))
        self.groupBox_2_7.setTitle(_translate("Editor", "Αναγνωριστικό (*)", None))
        self.groupBox_2_10.setTitle(_translate("Editor", "Xώρος ονομάτων", None))
        self.groupBox_2_9.setTitle(_translate("Editor", "Kωδικός (*)", None))
        self.pushButton_2_random.setText(_translate("Editor", "Δημιουργία\n"
"τυχαίου", None))
        self.groupBox_2_6.setTitle(_translate("Editor", "Γλώσσα γεωγραφικών δεδομένων", None))
        self.toolButton_2_11.setText(_translate("Editor", " i ", None))
        self.groupBox_2_5.setTitle(_translate("Editor", "Διέυθυνση URL γεωγραφικών δεδομένων", None))
        self.toolButton_2_8.setText(_translate("Editor", " - ", None))
        self.toolButton_2_6.setText(_translate("Editor", " i ", None))
        self.toolButton_2_7.setText(_translate("Editor", " +", None))
        self.groupBox_2_13.setTitle(_translate("Editor", "Διέυθυνση URL γεωγραφικών δεδομένων- Link 1 (*)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Editor", "Ταυτοποίηση", None))
        self.groupBox_3_1.setTitle(_translate("Editor", "ΚΑΤΗΓΟΡΙΟΠΟΙΗΣΗ ΧΩΡΙΚΩΝ ΔΕΔΟΜΕΝΩΝ ΚΑΙ ΥΠΗΡΕΣΙΩΝ", None))
        self.groupBox_3_2.setTitle(_translate("Editor", "Θεματική κατηγορία (*)", None))
        self.toolButton_3_1.setText(_translate("Editor", " i ", None))
        self.toolButton_3_2.setText(_translate("Editor", "+", None))
        self.toolButton_3_3.setText(_translate("Editor", " - ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Editor", "Κατηγοριοποίηση", None))
        self.groupBox_4_1.setTitle(_translate("Editor", "ΛΕΞΗ ΚΛΕΙΔΙ", None))
        self.groupBox_4_2.setTitle(_translate("Editor", "Τιμή της λέξης κλειδί (*)", None))
        self.toolButton_4_2.setText(_translate("Editor", " - ", None))
        self.pushButton.setText(_translate("Editor", "Προσθήκη INSPIRE Data themes keyword (*)", None))
        self.pushButton_2.setText(_translate("Editor", "Προσθήκη Free keyword (Προαιρετικό)", None))
        self.toolButton_4_1.setText(_translate("Editor", " - ", None))
        self.toolButton_4_3.setText(_translate("Editor", " i ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Editor", "Λέξη κλειδί", None))
        self.groupBox_5_1.setTitle(_translate("Editor", "ΓΕΩΓΡΑΦΙΚΗ ΘΕΣΗ", None))
        self.groupBox_5_2.setTitle(_translate("Editor", "Περίγραμμα γεωγραφικών συντεταγμένων (*)", None))
        self.label_9.setText(_translate("Editor", "πλάτος", None))
        self.label.setText(_translate("Editor", "N", None))
        self.label_10.setText(_translate("Editor", "μήκος", None))
        self.label_12.setText(_translate("Editor", "πλάτος", None))
        self.label_2.setText(_translate("Editor", "E", None))
        self.label_3.setText(_translate("Editor", "S", None))
        self.label_11.setText(_translate("Editor", "μήκος", None))
        self.label_5.setText(_translate("Editor", "Γεωγραφικό", None))
        self.pushButton_5_1.setText(_translate("Editor", "Επιλογή με βάση την έκταση του αρχείου", None))
        self.toolButton_5_1.setText(_translate("Editor", " i ", None))
        self.label_4.setText(_translate("Editor", "W", None))
        self.label_6.setText(_translate("Editor", "Γεωγραφικό", None))
        self.label_8.setText(_translate("Editor", "Γεωγραφικό", None))
        self.label_7.setText(_translate("Editor", "Γεωγραφικό", None))
        self.pushButton_5_2.setText(_translate("Editor", "Επιλογή περιοχής από το χάρτη", None))
        self.toolButton_5_2.setToolTip(_translate("Editor", "<html><head/><body><p>Zoom Out</p></body></html>", None))
        self.toolButton_5_2.setText(_translate("Editor", " - ", None))
        self.toolButton_5_3.setToolTip(_translate("Editor", "<html><head/><body><p>Zoom In</p></body></html>", None))
        self.toolButton_5_3.setText(_translate("Editor", "+", None))
        self.toolButton_5_4.setToolTip(_translate("Editor", "<html><head/><body><p>Refresh</p></body></html>", None))
        self.toolButton_5_4.setText(_translate("Editor", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Editor", "Γεωγραφική", None))
        self.groupBox_6_1.setTitle(_translate("Editor", "ΧΡΟΝΙΚΗ ΑΝΑΦΟΡΑ (Πρέπει να δοθεί τουλάχιστον μία από τις παρακάτω)", None))
        self.groupBox_6_2.setTitle(_translate("Editor", "Ημερομηνία δημιουργίας", None))
        self.dateEdit_6_1.setDisplayFormat(_translate("Editor", "d/M/yyyy", None))
        self.toolButton_6_1.setText(_translate("Editor", " i ", None))
        self.groupBox_6_3.setTitle(_translate("Editor", "Ημερομηνία δημοσίευσης", None))
        self.dateEdit_6_2.setDisplayFormat(_translate("Editor", "d/M/yyyy", None))
        self.toolButton_6_2.setText(_translate("Editor", " i ", None))
        self.groupBox_6_4.setTitle(_translate("Editor", "Ημερομηνία τελευταίας αναθεώρησης", None))
        self.dateEdit_6_3.setDisplayFormat(_translate("Editor", "d/M/yyyy", None))
        self.toolButton_6_3.setText(_translate("Editor", " i ", None))
        self.groupBox_6_5.setTitle(_translate("Editor", "Χρονική έκταση", None))
        self.groupBox_6_6.setTitle(_translate("Editor", "Ημερομηνία έναρξης", None))
        self.dateEdit_6_4.setDisplayFormat(_translate("Editor", "d/M/yyyy", None))
        self.groupBox_6_7.setTitle(_translate("Editor", "Ημερομηνία λήξης", None))
        self.radioButton.setText(_translate("Editor", "Τώρα", None))
        self.dateEdit_6.setDisplayFormat(_translate("Editor", "d/M/yyyy", None))
        self.radioButton_2.setText(_translate("Editor", "Προσδιόρισε ημερομηνία", None))
        self.toolButton_6_4.setText(_translate("Editor", " i ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Editor", "Χρονική", None))
        self.groupBox_7_1.setTitle(_translate("Editor", "ΠΟΙΟΤΗΤΑ ΚΑΙ ΕΓΚΥΡΟΤΗΤΑ", None))
        self.groupBox_7_3.setTitle(_translate("Editor", "Χωρική ανάλυση", None))
        self.radioButton_7_1.setText(_translate("Editor", "Ισοδύναμη κλίμακα", None))
        self.toolButton_7_2.setText(_translate("Editor", " i ", None))
        self.radioButton_7_2.setText(_translate("Editor", "Απόσταση χωρικής", None))
        self.comboBox_7_1.setItemText(0, _translate("Editor", "m", None))
        self.comboBox_7_1.setItemText(1, _translate("Editor", "km", None))
        self.comboBox_7_1.setItemText(2, _translate("Editor", "in", None))
        self.groupBox_7_2.setTitle(_translate("Editor", "Προέλευση", None))
        self.toolButton_7_1.setText(_translate("Editor", " i ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Editor", "Ποιότητα-εγκυρότητα", None))
        self.groupBox_8_1.setTitle(_translate("Editor", "Συμμορφωση", None))
        self.groupBox_8_2.setTitle(_translate("Editor", "Συμμορφωση", None))
        self.groupBox_8_5.setTitle(_translate("Editor", "Τύπος ημερομηνίας (*)", None))
        self.comboBox_8_2.setItemText(0, _translate("Editor", "Ημερομηνία δημιουργίας", None))
        self.comboBox_8_2.setItemText(1, _translate("Editor", "Ημερομηνία δημοσίευσης", None))
        self.comboBox_8_2.setItemText(2, _translate("Editor", "Ημερομηνία τελευταίας αναθεώρησης", None))
        self.groupBox_8_4.setTitle(_translate("Editor", "Ημερομηνία (*)", None))
        self.dateEdit_8_1.setDisplayFormat(_translate("Editor", "d/M/yyyy", None))
        self.groupBox_8_6.setTitle(_translate("Editor", "Βαθμός συμμόρφωσης (*)", None))
        self.comboBox_8_3.setItemText(0, _translate("Editor", "Δεν αξιολογήθηκε", None))
        self.comboBox_8_3.setItemText(1, _translate("Editor", "Δεν είναι σύμμορφος", None))
        self.comboBox_8_3.setItemText(2, _translate("Editor", "Σύμμορφος", None))
        self.groupBox_8_3.setTitle(_translate("Editor", "Προδιαγραφές", None))
        self.checkBox_8_1.setText(_translate("Editor", "Επιλογή μιας από τις προτάσεις -παραδείγματα", None))
        self.toolButton_8_1.setText(_translate("Editor", " i ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Editor", "Συμμόρφωση", None))
        self.groupBox_9_1.setTitle(_translate("Editor", "ΠΕΡΙΟΡΙΣΜΟΙ ΣΧΕΤΙΚΑ ΜΕ ΤΗΝ ΠΡΟΣΒΑΣΗ ΚΑΙ ΧΡΗΣΗ", None))
        self.groupBox_9_3.setTitle(_translate("Editor", "Περιορισμοί σχετικά με την πρόσβαση του κοινού (*)", None))
        self.toolButton_9_2.setText(_translate("Editor", " - ", None))
        self.groupBox_9_2.setTitle(_translate("Editor", "Όροι για την πρόσβαση και τη χρήση (*)", None))
        self.toolButton_9_1.setText(_translate("Editor", "+", None))
        self.toolButton_9_5.setText(_translate("Editor", " i ", None))
        self.toolButton_9_6.setText(_translate("Editor", " i ", None))
        self.toolButton_9_3.setText(_translate("Editor", "+", None))
        self.toolButton_9_4.setText(_translate("Editor", " - ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("Editor", "Περιορισμοί", None))
        self.groupBox_10_1.setTitle(_translate("Editor", "Αρμόδιο μέρος", None))
        self.label_10_2.setText(_translate("Editor", "ΚΑΙ ΤΗ ΔΙΑΝΟΜΗ ΤΩΝ ΣΥΝΟΛΩΝ ΚΑΙ ΥΠΗΡΕΣΙΩΝ ΧΩΡΙΚΩΝ ΔΕΔΟΜΕΝΩΝ", None))
        self.toolButton_10_3.setText(_translate("Editor", "+", None))
        self.groupBox_10_2.setTitle(_translate("Editor", "Αρμόδιο μέρος 1 (*)", None))
        self.groupBox_10_5.setTitle(_translate("Editor", "Ρόλος του αρμόδιου μέρους (*)", None))
        self.groupBox_10_4.setTitle(_translate("Editor", "Ηλεκτρονική διεύθυνση (*)", None))
        self.groupBox_10_3.setTitle(_translate("Editor", "Oνομασία του οργανισμού (*)", None))
        self.checkBox_10.setText(_translate("Editor", "Επιλογή από λίστα", None))
        self.groupBox_10_6.setTitle(_translate("Editor", "Ιστότοπος (Προαιρετικό)", None))
        self.groupBox_10_7.setTitle(_translate("Editor", "Τηλέφωνο (Προαιρετικό)", None))
        self.toolButton_10_5.setText(_translate("Editor", " - ", None))
        self.toolButton_10_4.setText(_translate("Editor", " i ", None))
        self.label_10_1.setText(_translate("Editor", "ΟΡΓΑΝΙΣΜΟΙ ΠΟΥ ΕΙΝΑΙ ΑΡΜΟΔΙΟΙ ΓΙΑ ΤΗ ΔΗΜΙΟΥΡΓΙΑ, ΤΗ ΔΙΑΧΕΙΡΙΣΗ, ΤΗ ΣΥΝΤΉΡΗΣΗ ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("Editor", "Αρμόδιος", None))
        self.label_13.setText(_translate("Editor", "(*) Υποχρεωτικό", None))

